- hosts: all
  become: yes
  gather_facts: false
  module_defaults:
    apt:
      force_apt_get: yes
  vars:
    cluster_id: "{{ cluster_id }}"
    nfs_mountpoint: "/mnt/worker"
    nfs_server: "{{ nfs_server }}"
    nfsexport: "/home/export"

  tasks:
    - name: Transfer the preRequisite.sh script
      copy: src=./scripts/preRequisite.sh dest=/home/{{ansible_user}} mode=0777

    - name: Execute the preRequisite.sh script
      command: sudo sh /home/{{ansible_user}}/preRequisite.sh

    - name: Copy join command to node
      copy: src=~/.fabdep/join-command/{{ cluster_id }} dest=/tmp/join-command.sh mode=0777

    - name: check if kubelet.conf file exits
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: stat_result

    - name: Join the node to cluster
      command: sh /tmp/join-command.sh mode=0777
      when: stat_result.stat.exists == False

    - name: Install docker prerequisite
      shell: sudo apt -y install docker.io
      args:
        chdir: $HOME
      
    - name: Create mount for nfs
      file:
        path: "{{nfs_mountpoint}}"
        state: directory
        mode: 777
        owner: nobody
        group: nogroup

    # - name: Check if drives are already mounted
    #   command: findmnt /mnt/worker
    #   register: mount_result

    # - name: Mount the NFS to the worker
    #   shell: |
    #     mount {{ nfs_server }}:/{{ nfsexport }} {{ nfs_mountpoint }}
    #   when: mount_result.stdout == ""

    - name: Mount the NFS to the worker
      mount:
        path: "{{ nfs_mountpoint }}"
        src: "{{ nfs_server }}:/{{ nfsexport }}"
        state: mounted
        fstype: nfs4
